baseURL = "/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Angelo Pana"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 3
[[menu.main]]
name = "Skills"
url = "#skill"
weight = 4



# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1


[params]
# blogPageURL = "blog"
contactLink = "contact"
copyright = "© Angelo Pana"
footerLogo = "images/site-navigation/white_logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo_tran.png"

[params.address]
address = "Sottsdale, AZ"
email = "angelo2.0ken@gmail.com"
openingHours = ""
phone = "(209) 762-2030"

[params.map]
APIkey = "AIzaSyDuDke_qeoNH1ucEsSTkm-0cj0f42z8RYQ"
latitude = "33.501324"
longitude = "-111.925278"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/angelopana/"
weight = 1
[[params.social]]
icon = "fa-github"
url = "https://github.com/angelopana"
weight = 2
[[params.social]]
icon = "fa-download"
url = "/"
weight = 3


